# Generated by Django 2.2.6 on 2019-10-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
